# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_config.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 313)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(30, 20, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 20, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 40, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.myframe = QtWidgets.QFrame(Dialog)
        self.myframe.setGeometry(QtCore.QRect(30, 70, 191, 71))
        self.myframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.myframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.myframe.setObjectName("myframe")
        self.lineEdit_in_myframe = QtWidgets.QLineEdit(self.myframe)
        self.lineEdit_in_myframe.setGeometry(QtCore.QRect(20, 10, 91, 20))
        self.lineEdit_in_myframe.setObjectName("lineEdit_in_myframe")
        self.lineEdit_2_in_myframe = QtWidgets.QLineEdit(self.myframe)
        self.lineEdit_2_in_myframe.setGeometry(QtCore.QRect(20, 40, 91, 20))
        self.lineEdit_2_in_myframe.setObjectName("lineEdit_2_in_myframe")
        self.spinBox_in_myframe = QtWidgets.QSpinBox(self.myframe)
        self.spinBox_in_myframe.setGeometry(QtCore.QRect(130, 10, 42, 22))
        self.spinBox_in_myframe.setObjectName("spinBox_in_myframe")
        self.doubleSpinBox_in_myframe = QtWidgets.QDoubleSpinBox(self.myframe)
        self.doubleSpinBox_in_myframe.setGeometry(QtCore.QRect(120, 40, 62, 22))
        self.doubleSpinBox_in_myframe.setObjectName("doubleSpinBox_in_myframe")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(230, 90, 41, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(200, 150, 111, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(230, 120, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(280, 90, 71, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(230, 10, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 140, 153, 52))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_5_in_groupbox = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5_in_groupbox.setObjectName("lineEdit_5_in_groupbox")
        self.verticalLayout_2.addWidget(self.lineEdit_5_in_groupbox)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 200, 173, 86))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.doubleSpinBox_3_in_myframe2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_3_in_myframe2.setObjectName("doubleSpinBox_3_in_myframe2")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_3_in_myframe2)
        self.frame_in_frame2 = QtWidgets.QFrame(self.frame_2)
        self.frame_in_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_in_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_in_frame2.setObjectName("frame_in_frame2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_in_frame2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_in_frame2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.verticalLayout_3.addWidget(self.frame_in_frame2)
        self.frame3 = QtWidgets.QFrame(Dialog)
        self.frame3.setGeometry(QtCore.QRect(370, 10, 173, 131))
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_in_frame3 = QtWidgets.QGroupBox(self.frame3)
        self.groupBox_in_frame3.setObjectName("groupBox_in_frame3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_in_frame3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_in_frame3)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_4)
        self.verticalLayout_6.addWidget(self.groupBox_in_frame3)
        self.frame_in_frame3 = QtWidgets.QFrame(self.frame3)
        self.frame_in_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_in_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_in_frame3.setObjectName("frame_in_frame3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_in_frame3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_in_frame3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_7.addWidget(self.lineEdit_7)
        self.verticalLayout_6.addWidget(self.frame_in_frame3)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 150, 171, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vLayout = QtWidgets.QVBoxLayout()
        self.vLayout.setObjectName("vLayout")
        self.spinBox_2_in_groupbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2_in_groupbox.setObjectName("spinBox_2_in_groupbox")
        self.vLayout.addWidget(self.spinBox_2_in_groupbox)
        self.spinBox_3_in_groupbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3_in_groupbox.setObjectName("spinBox_3_in_groupbox")
        self.vLayout.addWidget(self.spinBox_3_in_groupbox)
        self.spinBox_4_in_groupbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_4_in_groupbox.setObjectName("spinBox_4_in_groupbox")
        self.vLayout.addWidget(self.spinBox_4_in_groupbox)
        self.spinBox_5_in_groupbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_5_in_groupbox.setObjectName("spinBox_5_in_groupbox")
        self.vLayout.addWidget(self.spinBox_5_in_groupbox)
        self.horizontalLayout.addLayout(self.vLayout)
        self.frame_in_groupbox2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_in_groupbox2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_in_groupbox2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_in_groupbox2.setObjectName("frame_in_groupbox2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_in_groupbox2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_in_groupbox2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_8.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_in_groupbox2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_8.addWidget(self.lineEdit_4)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_in_groupbox2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_8.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_in_groupbox2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_8.addWidget(self.lineEdit_9)
        self.horizontalLayout.addWidget(self.frame_in_groupbox2)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 180, 141, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_in_gridLayout = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_in_gridLayout.setObjectName("lineEdit_in_gridLayout")
        self.gridLayout.addWidget(self.lineEdit_in_gridLayout, 0, 0, 1, 1)
        self.hLayout = QtWidgets.QHBoxLayout()
        self.hLayout.setObjectName("hLayout")
        self.lineEdit_in_hLayout = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_in_hLayout.setObjectName("lineEdit_in_hLayout")
        self.hLayout.addWidget(self.lineEdit_in_hLayout)
        self.gridLayout.addLayout(self.hLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_2.setText(_translate("Dialog", "RadioButton"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_2.setText(_translate("Dialog", "CheckBox"))
        self.comboBox.setItemText(0, _translate("Dialog", "01"))
        self.comboBox.setItemText(1, _translate("Dialog", "02"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.groupBox_in_frame3.setTitle(_translate("Dialog", "groupBox_in_frame3"))
        self.groupBox_2.setTitle(_translate("Dialog", "groupBox_2"))

